version: '3.8'

services:
  postgres:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    environment:
      POSTGRES_LOG_STATEMENT: none
      POSTGRES_LOG_DURATION: "off"

  hasura:
    restart: always
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_LOG_LEVEL: warn
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G