version: 3
metadata_directory: metadata
endpoint: http://localhost:8080
admin_secret: 
  from_env: HASURA_ADMIN_SECRET
actions:
  kind: synchronous
  handler_webhook_baseurl: 
    from_env: ACTION_BASE_URL